---
title: "Remote Access"
---

How to configure remote access to your server.

## Connecting Within Your Local Network

To connect to your server from your home network, you'll need to find out the IP address of the server.  On Windows, open the command prompt and type `ipconfig`.  If you're using WiFi, look for the section labeled "Wireless Lan Adapter Wi-Fi"; If you're using ethernet, look for "Ethernet Adapter Ethernet".  In the respective section, your local IP address will be indicated by "IPv4 Address".

On Linux, open the terminal and type `hostname -I`.  This will return the IP addresses of your network interface, one of which is your local IP.  If more than one address is shown, look for an address starting with "192.168.X.X", "172.16.X.X"-"172.31.X.X", or "10.X.X.X"

Once you have the server IP address, enter `http://[IP address]:8096` into your browser.  If the server does not load, ensure that your device is on the same network as the server; For example, if you have a main and a guest network, the device and server must be on the same one.  Otherwise, simply log into your server and enjoy!

## Connecting Outside Your Network

Most users will want access to their media library outside of their home network.  To do this, there are two main options: Port forwarding, and tunneling.

### Port Forwarding

Port forwarding involves opening a specific port on your router and directing traffic on that port to your server.  This allows you to access your server from anywhere with an internet connection by entering your public IP address and the forwarded port into your browser.

I personally have not used port forwarding due to moving between networks and having little to no access to the the routers.  However, here is a good source on how to set up port forwarding: [How to Set Up Port Forwarding](https://portforward.com/how-to-port-forward/).

If you move your server between networks relatively frequently or do not have access to the router, I recommend using a tunneling service instead.

### Tunneling

Tunneling services create a secure connection between your server and an external server, allowing you to access your server without needing to open ports on your router.  This is particularly useful if you are unable to configure port forwarding on your router, or if you want to avoid the security risks associated with opening ports.

Below are some tunneling services I've used; I've also linked a GitHub page with a more comprehensive list.

* Playit.gg: Playit.gg provides limited capabilities in exchange for free use.  This service will work when starting out, although other options are better if more configurability or easier sharing are desired.

* Localtonet: Localtonet is a paid tunneling service with a free tier.  Like Playit.gg, the free tier is quite limited, but sufficient for trying out the service.  Paid plans allow you to use custom domains and keep the tunnel open 24/7.

* Pinggy: Like Localtonet, Pinggy is a paid tunneling service with a free tier.  The free tier is still quite limited, but is still sufficient for testing out the service.  Pinggy also allows custom domains and 24/7 tunnels on paid plans.

* Other Options: There are many other tunneling services available, including those at different prices, having different capabilities, and some being open-source.  A good list of options is [anderspitman's awesome-tunneling on GitHub](https://github.com/anderspitman/awesome-tunneling).